### PR TITLE
Adding job summary to Reusable Workflow

### PR DESCRIPTION
**Pull request by Gordonby**
Added markdown job summary output, consuming workflows will now get a nice cost summary in their workflow run.

image

### CODE REVIEW

**Comment by kamil-mrzyglod** [comment]
I may need to add rounding to the estimate :)

**Comment by kamil-mrzyglod** [comment]
Love it!

**Comment by Gordonby** [comment]
> I may need to add rounding to the estimate :)

I was going to round in the bash script, but felt like the proper option was to delay what was in the json.

Adding a currency symbol might also be useful 😄

**Comment by kamil-mrzyglod** [comment]
> Adding a currency symbol might also be useful 😄

You mean like $ or €?

**Pull request merged**
